### ISSUE TITLE
Does not collect plugins when using `lld`

### ISSUE THREAD

**Issue by azriel91** [dtolnay/inventory#11]
When using [LLVM's linker `lld`](https://lld.llvm.org), no plugins are collected.

Haven't investigated very much after discovering that, but since `lld` is much faster than `gnu`'s `ld`, figured that other people using `lld` would run into this problem which is a hard one to discover.

<sub>I realize that it may not be an `inventory` crate issue, but this would be one of the first places people may look.</sub>

**Comment by dtolnay** [comment]
Thanks! The platform-specific heavy lifting is all handled by the `ctor` crate. Are you able to reproduce this directly using `ctor` without `inventory`?

The following is supposed to print `SUCCESS.load(SeqCst) = true`.

```rust
// [dependencies]
// ctor = "0.1.9"

use ctor::ctor;
use std::sync::atomic::{AtomicBool, Ordering::SeqCst};

static SUCCESS: AtomicBool = AtomicBool::new(false);

#[ctor]
fn init() {
    SUCCESS.store(true, SeqCst);
}

fn main() {
    dbg!(SUCCESS.load(SeqCst));
}
```

If it prints `false` using ld, this issue is something that would need to be fixed in `ctor`. If it prints true, then we'll need to debug more in `inventory`.

**Comment by azriel91** [comment]
ah, it prints `[src/main.rs:12] SUCCESS.load(SeqCst) = false`.

**Comment by azriel91** [comment]
The current `master`  of `ctor` now supports LLD (Thanks to https://github.com/mmastrac/rust-ctor/pull/19 :bowing_man:)!
Simply need to wait for a release.
